### ISSUE TITLE
installation of scipion-em-pyseg

### ISSUE THREAD

**Issue by zyzhang1992** [scipion-em/scipion-em-pyseg#61]
I am having problem installing scipion-em-pyseg and didn't have a clue about what the errors might be. I have git cloned the scipion-em-pyseg repo and ran the following command for installation: 

./scipion3 installp -p scipion-em-pyseg --devel 
Scipion v3.0.11 - Eugenius
```
Error retrieving plugin  binaries:  could not convert string to float: '/share/software/user/open/gcc/10.1.0/bin/gcc'
Building scipion-em-pyseg ...
/home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/scipion3/bin/python -m pip install -e scipion-em-pyseg
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///home/groups/ruthm/zyzhang/sw/Scipion3-Ticket61654/scipion-em-pyseg
Requirement already satisfied: scipion-em-tomo in /home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/scipion3/lib/python3.8/site-packages (from scipion-em-pyseg==3.0.5) (3.0.15)
Requirement already satisfied: scipion-em-tomoviz in ./scipion-em-tomoviz (from scipion-em-pyseg==3.0.5) (3.0.4)
Requirement already satisfied: scipion-em-reliontomo in /home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/scipion3/lib/python3.8/site-packages (from scipion-em-pyseg==3.0.5) (3.0.3)

.....

Requirement already satisfied: typing-extensions>=3.6.5 in /home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/scipion3/lib/python3.8/site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp<4->wslink>=1.0.4->vtk->pyvista==0.27.4->scipion-em-tomoviz->scipion-em-pyseg==3.0.5) (4.4.0)
Installing collected packages: scipion-em-pyseg
  Attempting uninstall: scipion-em-pyseg
    Found existing installation: scipion-em-pyseg 3.0.5
    Uninstalling scipion-em-pyseg-3.0.5:
      Successfully uninstalled scipion-em-pyseg-3.0.5
  Running setup.py develop for scipion-em-pyseg
Successfully installed scipion-em-pyseg
Done (23.39 seconds)
Couldn't get binaries definition of  plugin: could not convert string to float: '/share/software/user/open/gcc/10.1.0/bin/gcc'
```

Is this suppose to install the pyseg_system automatically? Or do I need to install pyseg_system separately and make sure that scipion3 can link to it? If you any advices on how to do that? I am installing with CentOS 7. 

Thansk!

**Comment by JorMaister** [comment]
Hi @zyzhang1992,

First of all, sorry for the delay in the response. I'm not sure about the error, because it seems you had a previous installation of PySeg. What it's mandatory for a successful compilation during the pyseg installation is that both gcc/g++ compilers point to a version lower or equal to 7.

Regarding your question, yes, the plugin automatically downloads the pyseg_system code. Apart from that it compiles DisPerSe and ctfsio programs and generates a conda environment containing all the required package dependencies. Thus, the pyseg_system corresponding version should be located in SCIPION_HOME/software/em/pySeg_Version/

Anything, let us know

**Comment by azazellochg** [comment]
I have exactly the same problem that comes from https://github.com/scipion-em/scipion-em-pyseg/blob/devel/pyseg/__init__.py#L182
This code expected smth like /path/to/gcc-7, which is not always the case
